site_name: "Ludic Framework"
site_description: Lightweight framework for building HTML pages in pure Python.
site_url: https://ludic.readthedocs.io/
repo_url: https://github.com/paveldedik/ludic

theme:
  name: "material"
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: deep purple
  features:
    - content.code.copy
    - content.action.edit

nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - Components: components.md
  - CSS Styles: styles.md
  - HTMX Support: htmx.md
  - Web Framework: web.md
  - Component Catalog: catalog.md
  - Examples: examples.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
