[tool.poetry]
name = "ludic"
version = "0.1.0"
description = ""
authors = ["Pavel Dedik <dedikx@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
typeguard = "^4.1.5"
typing-extensions = "^4.9.0"
typing-inspect = "^0.9.0"
starlette = {version = "^0.37.0", optional = true}
python-multipart = {version = "^0.0.9", optional = true}

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pyright = "^1.1.350"

[tool.poetry.extras]
starlette = ["starlette", "python-multipart"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",     # flake8 rules
    "F",     # flake8 rules
    "B",     # flake8-bugbear
    "C4",    # flake8-comprehensions
    "I",     # isort
    "D2",    # pydocstyle
    "C901",  # maccabe complexity
    "S",     # flake8-bandit
    "UP",    # pyupgrade
    "T10",   # flake8-debugger
]
ignore = [
    "B904",
    "S101",
    "D203",
    "D211",
    "D213",
    "UP040",
]
fixable = ["ALL"]

[tool.ruff.lint.isort]
known-first-party = ["ludic"]

[tool.pyright]
reportMissingImports = false
